server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.qq.com
    username: 2435169750@qq.com
    password: liygplzrmyiteadb                   # 填写客户端的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ruoxi.gm.domain

logging:
  level:
    com:
      ruoxi: trace

pagehelper:
  #  方言
  helper-dialect: mysql
  #  分页合理化参数 自动纠错。
  reasonable: true
  #  支持接口传参
  support-methods-arguments: true

fdfs:
  # 读取时间
  so-timeout: 1500
  # 连接超时时间
  connect-timeout: 6000
  # 缩略图
  thumb-image:
  width: 150
  height: 150
  # Tracker 服务，确保 tracker storage nginx 已经启动
  tracker-list:
    - 34.80.47.178:22122
